// d LOGIN
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const ACTUALIZAR_CUENTA = "ACTUALIZAR_CUENTA";
export const CODIGO_VERFICACION = "CODIGO_VERFICACION";
export const MENSAJE_ALERTA = "MENSAJE_ALERTA";
export const BLOQUEAR = "BLOQUEAR";

// d REGISTRO
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const CERRAR_SESION = "CERRAR_SESION";

// d ALERTA
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
export const ABRIR_CARD = "ABRIR_CARD";
export const MOSTRAR_ALERTA2 = "MOSTRAR_ALERTA2";
export const OCULTAR_ALERTA2 = "OCULTAR_ALERTA2";

// d PRODUCTOS
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const PRODUCTO_SELECCIONADO = "PRODUCTO_SELECCIONADO";
export const PRODUCTOS_LISTA = "PRODUCTOS_LISTA";
export const OBTENER_PRODUCTOS_CATEGORIAS = "OBTENER_PRODUCTOS_CATEGORIAS";
export const OBTENER_PRODUCTOS_CLIENTE = "OBTENER_PRODUCTOS_CLIENTE";
export const PRODUCTOS_ERROR = "PRODUCTOS_ERROR";
export const CREAR_PRODUCTO = "CREAR_PRODUCTO";
export const OBTENER_PRODUCTOS_AGOTADOS = "OBTENER_PRODUCTOS_AGOTADOS";
export const LIMPIAR = "LIMPIAR";
export const ACTUALIZAR_PRODUCTO = "ACTUALIZAR_PRODUCTO";
export const LIMPIAR_PRODUCTO_ELEJIDO = "LIMPIAR_PRODUCTO_ELEJIDO";
export const MANTENER_ESTADO = "MANTENER_ESTADO";

// d PEDIDOS
export const OBTENER_PEDIDOS = "OBTENER_PEDIDOS";
export const PEDIDO_SELECCIONADO = "PEDIDO_SELECCIONADO";

// d reclamos
export const OBTENER_RECLAMOS = "OBTENER_RECLAMOS";
export const SELECCIONAR_REACLAMO = "SELECCIONAR_REACLAMO";

// d usuarios
export const REGISTRAR_USUARIOS = "REGISTRAR_USUARIOS";
export const OBTENER_USUARIOS = "OBTENER_USUARIOS";
export const SELECCIONAR_USUARIO = "SELECCIONAR_USUARIO";
export const USUARIO_ERROR = "USUARIO_ERROR";
export const SELECCIONAR_USUARIO_PEDIDO = "SELECCIONAR_USUARIO_PEDIDO";
export const REMOVER_USUARIO_PEDIDO = "REMOVER_USUARIO_PEDIDO";

// d lista
export const AGREGAR_PRODUCTOS = "AGREGAR_PRODUCTOS";
export const QUITAR_PRODUCTOS = "QUITAR_PRODUCTOS";
export const SELECIONAR_ITEM = "SELECIONAR_ITEM";
export const ACTUALIZAR_ITEM = "ACTUALIZAR_ITEM";
export const OBTENER_LISTA_CREADA = "OBTENER_LISTA_CREADA";
export const ELIMINAR_LISTA = "ELIMINAR_LISTA";

// d DB storage
export const OBTENER_LISTAS = "OBTENER_LISTAS";

// d Categorias
export const OBTENER_CATEGORIAS = "OBTENER_CATEGORIAS";
export const SELECCIONAR_CATEGORIA = "SELECCIONAR_CATEGORIA";

// d Gneros
export const OBTENER_GENEROS = "OBTENER_GENEROS";
export const SELECCIONAR_GENERO = "SELECCIONAR_GENERO";

// d Marcas
export const OBTENER_MARCAS = "OBTENER_MARCAS";
export const SELECCIONAR_MARCA = "SELECCIONAR_MARCA";
